[package]
name = "mina-runtime-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
mina-runtime = { workspace = true }
serde_json = { workspace = true }
wasm-bindgen = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
wasm-bindgen-test = { workspace = true }
